version: '3.8'
services:
  # AWSをエミュレータするLocalStack用のコンテナ
  localstack:
    container_name: "localstack"
    build:
      context: ./docker/localstack # Dockerfile パス
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,s3,iam,events # 使用するサービス
      - DEBUG=1 # デバッグ設定
      - LAMBDA_EXECUTOR=docker # コンテナ内でLambdaを動かす
      - DOCKER_HOST=unix:///var/run/docker.sock # Dockerソケット読み込み
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" #ホストのDockerソケットマウント
    # 使用するDockerネットワーク
    networks:
      - local-net
  # Terraform用コンテナ
  terraform:
    container_name: "terraform"
    build:
      context: ./docker/terraform # Dockerfile パス
    volumes:
      - ./infrastructures/local:/app/local # ローカル用のTerraform設定ファイルをボリュームとして設定
      - ./infrastructures/module:/app/module # # 共通のTerraformコードをボリュームとして設定
      - ./src:/app/src # アプリケーションコードをボリュームとして設定
    # Pythonプロジェクトビルド＆Terraform実行
    entrypoint: /bin/sh -c "pip install -r /app/src/requirements.txt -t /app/src/package &&
      cp /app/src/lambda_function.py /app/src/package/ && cd /app/src/package && zip -r /app/src/lambda_function.zip . &&
      cd /app/local && 
      terraform init &&
      terraform plan &&
      terraform apply -auto-approve"
    # 使用するDockerネットワーク
    networks:
      - local-net
# コンテナ間で通信を行うためのネットワークブリッジ
networks:
  local-net:
    driver: bridge