name: 'Terraform Deployment'

on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop  # 'dev' 環境を指定

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    # ランナーにクレデンシャルを設定
    - name: Set AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run:  | 
        pip install -r ./src/requirements.txt -t ./src/package &&
        cp ./src/lambda_function.py ./src/package/ && cd ./src/package && zip -r lambda_function.zip .

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        terraform init \
        -backend-config="bucket=${{ secrets.TERRAFORM_BACKEND_BUCKET }}" \
        -backend-config="key=terraform.tfstate" \
        -backend-config="region=${{ secrets.TERRAFORM_BACKEND_REGION }}"
      working-directory: ./infrastructures/dev
      
    - name: Terraform Plan
      run: terraform plan
      working-directory: ./infrastructures/dev

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./infrastructures/dev
